---
- name: Webserver preparation
  hosts: webserver
  become: true

  tasks:
    - name: Maven when cloned ok
      shell:
        cmd: for IM in (docker ps -q); do docker stop IM; done

    - name: Maven when cloned ok
      shell:
        cmd: for IM in (docker ps -a -q); do docker rm IM; done

    - name: Maven when cloned ok
      shell:
        cmd: for IM in (docker images -q); do docker rmi IM; done