---
- name: Webserver preparation
  hosts: webserver
  become: true

  tasks:
    - name: remove images 
      shell:
        cmd: docker rmi $(docker images -a -q)

    - name: stop containers
      shell:
        cmd: docker stop $(docker ps -a -q)

    - name: remove containers
      shell:
        cmd: docker rm $(docker ps -a -q)