---
- name: Webserver preparation
  hosts: webserver
  become: true

  tasks:
    - name: stop containers
      command: docker stop $(docker ps -a -q)
      register: result
      failed_when:
        - '"requires at least 1 argument" not in result.stdout'

    - name: remove images 
      command: docker rmi $(docker images -a -q) --force
      register: result
      failed_when:
        - '"requires at least 1 argument" not in result.stdout'

    - name: remove containers
      command: docker rm $(docker ps -a -q) --force
      register: result
      failed_when:
        - '"requires at least 1 argument" not in result.stdout'